---
- name: in this playbook i have write some html code that will display through webpackagei.e httpd
  hosts: all
  become: true
  tasks:
          - name: install httpd package
            yum:
                    name: httpd
                    state: present
       
          - name:  start service
            service:
                  name: httpd
                  state: started
          - name: copy index.html file
            copy:
                  src: /home/saurabh/index.html
                  dest: /var/www/html          
