---
- name: in this playbook we are going to use variables.
  hosts: all
  become: true
  vars: 
        user: sunny
  tasks:
          - name: here we create user= "{{user}}"
            user:
                    name: "{{user}}"
                    state: present

